
# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class *
# layerrule = blur on, match:namespace waybar
# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule {
    name= title_with_pin
    match:title = ^(nmtui|update)$
    
    float = on
    pin = on
    size = 900 600
    center = on
}

windowrule {
    name= title_without_pin
    match:title = ^(centfloa)$
    
    float = on
    pin = on
    size = 900 600
    center = on
}

windowrule {
    name= title_without_pin_larger_size
    match:title = ^(btop)$

    float = on
    size = 1200 700
    center = on
}

# Pulseaudio
windowrule {
    name= pulseaudio
    match:class = ^(org.pulseaudio.pavucontrol|waypaper|blueman-manager)$
    
    float = on
    pin = on
    size = 800 600
    center = on
}


# prevent full video from fullscreen
# windowrulev2 = suppressevent fullscreen, class:^(firefox|zen)$
windowrule = fullscreen_state 0 2, match:class ^(firefox|zen|spotify)$


layerrule = blur on, match:namespace logout_dialog

layerrule {
    name = swaync

    blur = on
    ignore_alpha = 0.3
    animation = slidefade right

    match:namespace = swaync-control-center
}
