
# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class *
# Fix some dragging issues with XWayland
# windowrule = no_focus on,match:namespace xwayland:1,floating:1,fullscreen:0,pinned:0

# network manager
windowrule = float on, match:title ^(nmtui)$
windowrule = pin on,  match:title ^(nmtui)$
windowrule = size 800 600,  match:title ^(nmtui)$
windowrule = center on, match:title ^(nmtui)$

# update window
windowrule = float on, match:title ^(update)$
windowrule = pin on, match:title ^(update)$
windowrule = size 800 600, match:title ^(update)$
windowrule = center on, match:title ^(update)$


# waypaper
windowrule = float on, match:class ^(waypaper)$
windowrule = pin on,  match:class ^(waypaper)$
windowrule = size 800 600,  match:class ^(waypaper)$
windowrule = center on, match:class ^(waypaper)$


# blueman-manager
windowrule = float on, match:class ^(blueman-manager)$
windowrule = pin on,  match:class ^(blueman-manager)$
windowrule = size 800 600,  match:class ^(blueman-manager)$
windowrule = center on, match:class ^(blueman-manager)$

# Pulseaudio
windowrule {
    name= pulseaudio
    match:class = ^(org.pulseaudio.pavucontrol)$
    
    float = on
    pin = on
    size = 800 600
    center = on
}

# btop
windowrule = float on, match:title ^(btop)$
windowrule = size 1200 700, match:title ^(btop)$
windowrule = center on, match:title ^(btop)$


# prevent full video from fullscreen
# windowrulev2 = suppressevent fullscreen, class:^(firefox|zen)$
windowrule = fullscreen_state 0 2, match:class ^(firefox|zen)$
windowrule = fullscreen_state 0 2, match:class ^(spotify)$


layerrule = blur on, match:namespace logout_dialog

layerrule {
    name = swaync

    blur = on
    ignore_alpha = 0.3
    animation = slidefade right

    match:namespace = swaync-control-center
}
