
# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:namespace class:.*
# layerrule = blur on, match:namespace waybar
# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# network manager
windowrulev2 = float, title:^(nmtui)$
windowrulev2 = pin,  title:^(nmtui)$
windowrulev2 = size 800 600,  title:^(nmtui)$
windowrulev2 = center, title:^(nmtui)$

# update window
windowrulev2 = float, match:namespace title:^(update)$
windowrulev2 = pin,  match:namespace title:^(update)$
windowrulev2 = size 800 600,  match:namespace title:^(update)$
windowrulev2 = center, match:namespace title:^(update)$


# waypaper
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = pin,  class:^(waypaper)$
windowrulev2 = size 800 600,  class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$


# blueman-manager
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = pin,  class:^(blueman-manager)$
windowrulev2 = size 800 600,  class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$

# Pulseaudio
windowrule {
    name= pulseaudio
    match:class = ^(org.pulseaudio.pavucontrol)$
    
    float = on
    pin = on
    size = 800 600
    center = on
}

# btop
windowrule = float on, match:title btop
windowrule = size 1200 700, match:title btop
windowrule = center on, match:title btop


# prevent full video from fullscreen
# windowrulev2 = suppressevent fullscreen, class:^(firefox|zen)$
windowrulev2 = fullscreenstate 0 2, class:^(firefox|zen)$


layerrule = blur on, match:namespace logout_dialog
